/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "reicicjgssxjwktdukpe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaWNpY2pnc3N4andrdGR1a3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0ODA5MjUsImV4cCI6MjA3ODA1NjkyNX0.zzmuD-8ff_kDnxpEV-g-3pBBBuQGUqIpep1Td6njjKs"